fix nvuti game
vachrameev/4tune pull request #3
Opened 2019-07-25 11:29 UTC by vachrameev

2019-07-25 11:48 UTC, dentriger requested changes

2019-07-25 11:48 UTC, dentriger commented on app/Http/Controllers/NvutiController.php
>              ['status', '=', 'в процессе'], // статус изменить
Плиз, русский не юзай в коде. Let's speak English

2019-07-25 11:48 UTC, dentriger commented on app/Http/Controllers/NvutiController.php
> +        //$result =$this->createNewGame($userData);
Удаляй не нужный код, а не комментируй

2019-07-25 11:48 UTC, dentriger commented on app/Http/Controllers/NvutiController.php
> +        $number = $this->getChance($request['amount'], $request['chance']);
Плиз, параметры являются обязательными, нужна валидация на них

2019-07-25 11:48 UTC, dentriger commented on app/Http/Controllers/NvutiController.php
>          $newGame = Nvuti_game::find($nvuti_game->id);
PSR стандарты. Все в CamelCase писать, никаких _

2019-07-25 11:48 UTC, dentriger commented on app/Http/Controllers/NvutiController.php
> +        return response()->json(['success' => true, 'hash' => $this->createNewGame($userData)]);
Запихнуть в переменную $hash, а не вызывать метод в ответе

2019-07-25 11:48 UTC, dentriger commented on app/Http/Controllers/NvutiController.php
> +    private  function getChance($amount, $chance)
Название метода говорит о том что будет возвращен шанс, а по факту....

2019-07-25 11:48 UTC, dentriger commented on app/Http/Controllers/NvutiController.php
>      public function game($userData) // проверка на существование игры
Проверка на существование игры? isGameExist

2019-07-25 11:48 UTC, dentriger commented on app/Http/Controllers/NvutiController.php
> +    private function isNumberMore($number, $from, $to)
Туть тоже не ясно что происходит в методе

2019-07-25 11:48 UTC, dentriger commented on app/Http/Controllers/NvutiController.php
> +            'user_id' => $userData->id,
На сколько я понимаю, userData достаеться из user таблицы но используется только id поле. Передавать id, а не все данные, в случае если везде выше только id и нужен, доставать из базы только id.

2019-07-25 11:48 UTC, dentriger commented on public/js/bootstrap.js
> +    require('public/js/bootstrap');
???? Че за файл?

2019-07-25 11:48 UTC, dentriger commented on resources/js/app.js
> +Vue.component('example-component', require('../../public/js/components/ExampleComponent.vue'));
Ту даже в топку бесполезный файл

2019-07-25 11:48 UTC, dentriger commented on resources/views/header.blade.php
>      <title>Title</title>
Про blade темплейты мы уже обсуждали

2019-07-26 08:11 UTC, vachrameev commented on app/Http/Controllers/NvutiController.php
>              ['status', '=', 'в процессе'], // статус изменить
done

2019-07-26 08:11 UTC, vachrameev commented on app/Http/Controllers/NvutiController.php
> +        //$result =$this->createNewGame($userData);
done

2019-07-26 08:11 UTC, vachrameev commented on app/Http/Controllers/NvutiController.php
>          $newGame = Nvuti_game::find($nvuti_game->id);
done

2019-07-26 08:11 UTC, vachrameev commented on app/Http/Controllers/NvutiController.php
> +        return response()->json(['success' => true, 'hash' => $this->createNewGame($userData)]);
done

2019-07-26 08:12 UTC, vachrameev commented on app/Http/Controllers/NvutiController.php
> +    private  function getChance($amount, $chance)
done

2019-07-26 08:12 UTC, vachrameev commented on app/Http/Controllers/NvutiController.php
>      public function game($userData) // проверка на существование игры
done

2019-07-26 08:12 UTC, vachrameev commented on app/Http/Controllers/NvutiController.php
> +    private function isNumberMore($number, $from, $to)
done

2019-07-26 08:12 UTC, vachrameev commented on app/Http/Controllers/NvutiController.php
> +            'user_id' => $userData->id,
done

2019-07-26 08:12 UTC, vachrameev commented on public/js/bootstrap.js
> +    require('public/js/bootstrap');
removed

2019-07-26 08:12 UTC, vachrameev commented on resources/js/app.js
> +Vue.component('example-component', require('../../public/js/components/ExampleComponent.vue'));
removed

2019-07-31 11:02 UTC, closed without merging