Game nvuti
vachrameev/4tune pull request #7
Opened 2019-07-31 11:00 UTC by vachrameev

add Create wallets for new users, refactoring nvuti.js NvutiController. add NvutiRepository

2019-07-31 11:05 UTC, dentriger commented on app/Http/Controllers/NvutiController.php
> +        $this->nvutiRepository = new NvutiRepository();
Братан, если ты сделал это не статическим классом, то создание объекта должно быть при создании контроллера

2019-07-31 11:09 UTC, dentriger commented on app/NvutiGame.php
> + public Const STATUS_DONE = "done";
в константах слов publc не должно быть. и const, а не Const

2019-07-31 11:09 UTC, dentriger commented on app/NvutiGame.php
> + public Const STATUS_PLAYS = "plays";
Название Констант должно быть вида Клас_Название константы
т.е NVUTI_GAME_STATUS_PENDING

2019-07-31 11:09 UTC, dentriger commented on app/NvutiGame.php
> + public Const STATUS_DONE = "done";
Статусы pending, closed

2019-07-31 11:11 UTC, dentriger commented on app/Repositories/NvutiRepository.php
> +        $userId = $user->id;
если же ты тут подключаешь Auth зачем передавать user?

2019-07-31 11:20 UTC, vachrameev commented on app/Repositories/NvutiRepository.php
> +        $userId = $user->id;
а я тут и не подключаю, потому и передаю user

2019-07-31 11:50 UTC, dentriger requested changes

2019-07-31 11:50 UTC, dentriger commented on app/Http/Controllers/NvutiController.php
>          $chance = $request['chance'];
доставай данные $name = $request->input('name'); так а не так
https://laravel.com/docs/5.7/requests

2019-07-31 11:50 UTC, dentriger commented on app/Http/Controllers/NvutiController.php
> -            $hash = NvutiRepository::getNewHash();
Это какое то говно, валидация не так делается
https://laravel.com/docs/5.7/validation

2019-07-31 11:50 UTC, dentriger commented on app/Http/Controllers/NvutiController.php
> +            $user->depositFloat(1000);
Вот это убери, нам не надо чтобы деньги по воздуху приходили.
Если нужны бабки, так меняй это в бд пока

2019-08-01 10:59 UTC, dentriger commented on app/Http/Controllers/NvutiController.php
> +        if(!$request->has('chance') || !$request->has('amount') || !$request->has('stake')) {
уже лучше, однако я скидывал доку по валидации https://laravel.com/docs/5.7/validation
Должно быть что то вроде это 
$request->validate([
    'title' => 'required|unique:posts|max:255',
    'author.name' => 'required',
    'author.description' => 'required',
]);

2019-08-01 11:00 UTC, dentriger commented on app/Http/Controllers/NvutiController.php
>              return response()->json(['success' => false, 'hash' => $hash, 'balance' => $balance]);
Если сделать так как описано ниже, при ошибке валидации он вернет ошибку и все, ничего апдейтать заново не нужно

2019-08-01 11:13 UTC, dentriger requested changes

2019-08-01 11:13 UTC, dentriger commented on app/Http/Controllers/NvutiController.php
> +            'chance' => 'required',
а если chance отправить -100; тогда получиться что при пройгрыше, будет выйгрыш

2019-08-01 11:13 UTC, dentriger commented on app/Http/Controllers/NvutiController.php
> +            'amount' => 'required',
а если amount будет -1000, получиться $user->balance - (-1000) и получаются халявные бабки

2019-08-01 11:13 UTC, dentriger commented on app/Http/Controllers/NvutiController.php
> +            'stake' => 'required',
Тут тоже самое. Придет строка "Вася пупкин" что в результате выполнение кода ниже произойдет?

2019-08-01 12:07 UTC, merged